version: "3.7"

x-env:
  environment: &default-env
    MAIL_DRIVER: smtp
    MAIL_HOST: mailhog
    MAIL_PORT: 1025
    REDIS_HOST: redis
    QUEUE_CONNECTION: redis
    SESSION_DRIVER: redis
    DB_CONNECTION: mysql
    DB_HOST: mysql
    DB_PORT: 3306
    DB_DATABASE: homestead
    DB_USERNAME: homestead
    DB_PASSWORD: secret
    BROADCAST_DRIVER: log
    CACHE_DRIVER: redis
    SESSION_DRIVER: redis
    QUEUE_DRIVER: redis
    APP_ENV: production
    APP_KEY: base64:WfpY+XDjPbQKYb9VDP7zyP4G7WBuB9rLHswC34DsNoc=
    APP_DEBUG: 1
    APP_LOG_LEVEL: debug
    APP_URL: http://localhost:${APP_PORT:-3000}
    BROADCAST_DRIVER: log
    CACHE_DRIVER: file
    SESSION_DRIVER: file
    QUEUE_DRIVER: file
    MAIL_FROM_ADDRESS: cronmon@example.org
    MAIL_FROM_NAME: Cronmon
    CRONMON_ADMIN_USERNAME: ${CRONMON_ADMIN_USERNAME}
    CRONMON_ADMIN_EMAIL: ${CRONMON_ADMIN_EMAIL}
    CRONMON_ADMIN_PASSWORD: ${CRONMON_ADMIN_PASSWORD}

services:
  app:
    image: ohffs/cronmon:2.0.3
    environment:
      CONTAINER_ROLE: app
      <<: *default-env
    ports:
      - "${APP_PORT:-3000}:80"
    depends_on:
      - redis
      - mysql
      - mailhog

  scheduler:
    image: ohffs/cronmon:2.0.3
    environment:
      CONTAINER_ROLE: scheduler
      <<: *default-env
    depends_on:
      - app

  queue:
    image: ohffs/cronmon:2.0.3
    environment:
      CONTAINER_ROLE: queue
      <<: *default-env
    depends_on:
      - app

  migrations:
    image: ohffs/cronmon:2.0.3
    environment:
      CONTAINER_ROLE: migrations
      <<: *default-env
    depends_on:
      - app

  redis:
    image: redis:5.0.4
    volumes:
      - redis:/data

  mysql:
    image: mysql:5.7
    volumes:
      - mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: homestead
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: homestead
      MYSQL_PASSWORD: secret

  mailhog:
    image: mailhog/mailhog
    ports:
      - "3025:8025"

volumes:
  redis:
    driver: "local"
  mysql:
    driver: "local"

